export enum ActionType {
  SET_USER = 'SET_USER',
  RESET_USER = 'RESET_USER',
  START_PLAYING = 'START_PLAYING',
  STOP_PLAYING = 'STOP_PLAYING',
  SET_SIZE = 'SET_SIZE',
  SET_SPEED = 'SET_SPEED',
  SET_FILL = 'SET_FILL',
  SET_MODEL = 'SET_MODEL',
  RESET_MODEL = 'RESET_MODEL',
}
